language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "foo"

before_script:
  - chmod +x buildscripts/javadocs_publish.sh
  - chmod +x buildscripts/jar_publish.sh
script:
  - mvn -f stateless-csrf/pom.xml test

after_success:
  - buildscripts/javadocs_publish.sh
  - buildscripts/jar_publish.sh